services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
    ports:
      - "1883:1883"
  analytics_service:
    container_name: analytics_service
    build: ./AnalyticsService
    restart: always
    depends_on:
      - "mqtt"
  