apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
    - host: app-mosquitto.com
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: mosquitto-service
                port:
                  number: 1883
    - host: app-grafana.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-service
                port:
                  number: 3000
    
    - host: app-gateway.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cars-service
                port:
                  number: 80