apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |-
    # =================================================================
    # Listeners
    # =================================================================
    listener 1883
    max_connections 1024
    protocol mqtt

    # -----------------------------------------------------------------
    # Certificate based SSL/TLS support
    # -----------------------------------------------------------------
    require_certificate false


    # =================================================================
    # Logging
    # =================================================================
    log_dest stderr
    log_type error
    log_type information
    connection_messages true


    # =================================================================
    # Security
    # =================================================================
    allow_anonymous true