apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: datastore-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: datastore-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80