apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kafkabridge-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kafka-bridge-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: External
    external:
      metric:
        name: broker_publish_messages_per_sec
      target:
        type: AverageValue
        averageValue: 1000m