apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mosquitto-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mosquitto-deployment
  minReplicas: 1
  maxReplicas: 2
  #targetCPUUtilizationPercentage: 50
  metrics:
  - type: Pods
    pods:
      metric:
        name: broker_publish_messages_per_sec
      target:
        type: AverageValue
        averageValue: 1000m