apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mosquitto-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mosquitto-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50