apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-deployment
  labels:
    app: cars
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cars
  template:
    metadata:
      labels:
        app: cars
    spec:
      containers:
      - name: cars
        image: urospes/cars_service:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cars-service
spec:
  selector:
    app: cars
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80