apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore-deployment
  labels:
    app: datastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datastore
  template:
    metadata:
      labels:
        app: datastore
    spec:
      containers:
      - name: datastore
        image: urospes/datastore_service:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: datastore-service
spec:
  selector:
    app: datastore
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80