apiVersion: apps/v1
kind: Deployment
metadata:
  name: defects-deployment
  labels:
    app: defects
spec:
  replicas: 1
  selector:
    matchLabels:
      app: defects
  template:
    metadata:
      labels:
        app: defects
    spec:
      containers:
      - name: defects
        image: urospes/defects_service:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: defects-service
spec:
  selector:
    app: defects
  ports:
    - protocol: TCP
      name: defects-service-port
      port: 80
      targetPort: 80
    - protocol: TCP
      name: grpc-port
      port: 85
      targetPort: 85