apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-bridge-deployment
  labels:
    app: kafka-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-bridge
  template:
    metadata:
      labels:
        app: kafka-bridge
    spec:
      containers:
      - name: kafka-bridge
        image: urospes/kafka_bridge_service:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-bridge-service
spec:
  selector:
    app: kafka-bridge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80