apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-bridge-deployment
  labels:
    app: kafka-bridge
spec:
  serviceName: kafka-bridge-headless
  replicas: 1
  selector:
    matchLabels:
      app: kafka-bridge
  template:
    metadata:
      labels:
        app: kafka-bridge
    spec:
      containers:
      - name: kafka-bridge
        image: urospes/kafka_bridge_service:latest
        ports:
        - containerPort: 80
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      initContainers:
      - name: init-mosquitto
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup mosquitto-deployment-${HOSTNAME##*-}.mosquitto-headless.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do sleep 1; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-bridge-service
spec:
  selector:
    app: kafka-bridge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-bridge-headless
spec:
  clusterIP: None
  selector:
    app: kafka-bridge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80