apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mosquitto-deployment
  labels:
    app: mosquitto
spec:
  serviceName: mosquitto-headless
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mqtt-exporter
        image: sapcc/mosquitto-exporter
        env:
        - name: BROKER_ENDPOINT
          value: tcp://localhost:1883
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9234     

      - name: mosquitto
        image: eclipse-mosquitto:latest
        volumeMounts:
        - name: mosquitto-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
        ports:
        - containerPort: 1883
        resources:
            limits:
              memory: "128Mi"
              cpu: "60m"
            requests:
              cpu: "20m"
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  labels:
    app: mosquitto-service
spec:
  selector:
    app: mosquitto
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
      name: nebitno
    - protocol: TCP
      port: 9234
      targetPort: 9234
      name: exporter-port

---

apiVersion: v1
kind: Service
metadata:
  name: mosquitto-headless
spec:
  clusterIP: None
  selector:
    app: mosquitto
  ports:
  - port: 1883
    targetPort: 1883
