apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: defects-monitor
  namespace: default
spec:
  endpoints:
  - interval: 30s
    port: defects-service-port
  selector:
    matchLabels:
      app: defects