apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: mosquitto-monitor
  namespace: default
spec:
  endpoints:
  - interval: 30s
    port: exporter-port
  selector:
    matchLabels:
      app: mosquitto-service